In [1]:
import numpy as np
from uncertainties import ufloat

In [23]:
i=np.array([ufloat(1.25, 0.01), ufloat(2.59,0.01),ufloat(2.91,0.01),ufloat(3.13, 0.01),ufloat(3.35, 0.01),ufloat(3.55, 0.01),
           ufloat(3.69, 0.01),ufloat(3.87, 0.01),ufloat(4.04, 0.01),ufloat(4.16, 0.01)])
mi=1.257*10**(-6)
n=154
B=0.8**(1.5)*mi*n*(i/0.2)

array([0.0008657071338969085+/-6.9256570711752675e-06,
       0.0017937451814343942+/-6.9256570711752675e-06,
       0.002015366207712003+/-6.9256570711752675e-06,
       0.0021677306632778585+/-6.9256570711752675e-06,
       0.0023200951188437147+/-6.9256570711752675e-06,
       0.00245860826026722+/-6.9256570711752675e-06,
       0.002555567459263674+/-6.9256570711752675e-06,
       0.0026802292865448283+/-6.9256570711752675e-06,
       0.0027979654567548084+/-6.9256570711752675e-06,
       0.002881073341608912+/-6.9256570711752675e-06], dtype=object)

In [3]:
U=np.array([ufloat(100, 5),ufloat(120, 5),ufloat(140, 5),ufloat(160, 5),ufloat(180, 5),ufloat(200, 5),
           ufloat(220, 5),ufloat(240, 5),ufloat(260, 5),ufloat(280, 5)])

In [24]:
(2*U)/(B**2*0.02**2) # e/m(0,02)

array([667156945468.321+/-35024151132.147736,
       186478924397.83276+/-7902264209.006588,
       172341589992.08228+/-6267991132.07593,
       170246951961.4167+/-5430295326.058688,
       167197942448.6213+/-4750445231.386465,
       165432688322.83304+/-4239532546.163582,
       168429432807.29086+/-3935291299.7877383,
       167046487958.53644+/-3585611421.052271,
       166057561205.09348+/-3297528078.3770213,
       168662839567.76437+/-3119083749.696764], dtype=object)

In [28]:
ii=np.array([ufloat(0.26, 0.01),ufloat(1.65, 0.01),ufloat(1.86, 0.01),ufloat(2.04, 0.01),ufloat(2.18, 0.01),ufloat(2.31, 0.01),
            ufloat(2.41, 0.01),ufloat(2.53, 0.01),ufloat(2.64, 0.01),ufloat(2.74, 0.01),ufloat(2.84, 0.01)])
mi=1.257*10**(-6)
n=154
r=0.2
B=0.8**(1.5)*mi*n*(ii/0.2)
u=np.array([ufloat(100, 5),ufloat(120, 5),ufloat(140, 5),ufloat(160, 5),ufloat(180, 5),ufloat(200, 5),
           ufloat(220, 5),ufloat(240, 5),ufloat(260, 5),ufloat(280, 5), ufloat(300,5)])
(2*u)/(B**2*0.03**2) # e/m(0,03)

array([6853601099896.459+/-628784183405.8213,
       204210880155.59265+/-8861516717.741867,
       187485491991.6178+/-6992808000.3580065,
       178125118936.17868+/-5833915482.756326,
       175478954177.97348+/-5133390607.983342,
       173648707615.29987+/-4594185346.026686,
       175490703599.55945+/-4245998437.695219,
       173714359300.59866+/-3870826009.014606,
       172834729298.35312+/-3572350399.952284,
       172791520084.7677+/-3333384869.7886515,
       172325717002.9511+/-3117958075.0359945], dtype=object)

In [30]:
iii=np.array([ufloat(1.17,0.01),ufloat(1.36,0.01),ufloat(1.49,0.01),ufloat(1.59,0.01),ufloat(1.70,0.01),ufloat(1.78,0.01),ufloat(1.87,0.01),
             ufloat(1.94,0.01),ufloat(2.07,0.01),ufloat(2.09,0.01)])
B=0.8**(1.5)*mi*n*(iii/0.2)
u=np.array([ufloat(120, 5),ufloat(140, 5),ufloat(160, 5),ufloat(180, 5),ufloat(200, 5),
           ufloat(220, 5),ufloat(240, 5),ufloat(260, 5),ufloat(280, 5), ufloat(300,5)])
(2*u)/(B**2*0.04**2) # e/m(0,04)

array([228453369996.54865+/-10288816792.38624,
       197259653196.90097+/-7618854199.959911,
       187817256392.8205+/-6387815275.380099,
       185552283249.2438+/-5658056356.908174,
       180351682922.88086+/-4983088946.000201,
       180955056183.51166+/-4587757117.566937,
       178861173146.65875+/-4188617093.333397,
       180035410973.87173+/-3928336797.6459737,
       170296368434.7304+/-3457597675.22758,
       178985038225.01514+/-3439824099.8587437], dtype=object)

In [31]:
iiii=np.array([ufloat(0.93,0.01),ufloat(1.07,0.01),ufloat(1.17,0.01),ufloat(1.27,0.01),ufloat(1.35,0.01),ufloat(1.42,0.01),ufloat(1.48,0.01),
              ufloat(1.54,0.01),ufloat(1.60,0.01),ufloat(1.65,0.01)])
B=0.8**(1.5)*mi*n*(iiii/0.2)
(2*u)/(B**2*0.04**2)

array([361579163126.69147+/-16954139366.447313,
       318675390473.39343+/-12845763862.493406,
       304604493328.7315+/-10849941589.52137,
       290839312593.7214+/-9286866023.274628,
       285989774291.97577+/-8310838916.543044,
       284337433054.86926+/-7602516557.3211975,
       285545852984.1814+/-7090758571.526704,
       285706389248.2979+/-6629896585.793139,
       285040198869.52185+/-6213141143.251097,
       287171550218.8021+/-5918114198.861934], dtype=object)