In [1]:
import pandas as pd
import numpy as np
from uncertainties import ufloat, unumpy

### Dados para Lâmpada de Hg

In [3]:
hg=np.array([ufloat(106.25,0.04),ufloat(137.50,0.04),ufloat(150.00,0.04),ufloat(155.50,0.04),ufloat(182.50,0.04)]) #l +/- delta l
d=np.array([ufloat(393.0,0.5)])
k=1/600
lbda=(k*hg/(d**2 + hg**2)**(1/2))*10**6 #Comprimento de Onda (nm)
lbda


array([434.97726631730825+/-0.5378157641283033,
       550.4057325193864+/-0.639992318313688,
       594.3139883522466+/-0.6743207640280131,
       613.2010016410197+/-0.6881974163637324,
       701.9651857131096+/-0.7454814194757303], dtype=object)

In [4]:
c=299792458
f=c/lbda*10**(-3)
f # Frequencia em 10^12 Hz

array([689.214083619043+/-0.8521599350876572,
       544.675391783716+/-0.6333292807843324,
       504.4344637271345+/-0.5723416235340855,
       488.89753473609716+/-0.5486912437709119,
       427.0759634545808+/-0.45355126142994423], dtype=object)

In [5]:
h=6.63*10**(-34)
E=h*f
E #Energia

array([4.569489374394255e-31+/-5.649820369631167e-34,
       3.6111978475260365e-31+/-4.198973131600124e-34,
       3.3444004945109017e-31+/-3.7946249640309867e-34,
       3.2413906553003236e-31+/-3.6378229462011462e-34,
       2.8315136377038703e-31+/-3.00704486328053e-34], dtype=object)

### Dados para Lâmpada de He

In [6]:
lHe=np.array([ufloat(112.00,0.04),ufloat(118.00,0.04),ufloat(124.00,0.04),ufloat(128.00,0.04),ufloat(146.00,0.04),ufloat(176.00,0.04)])
d=np.array([ufloat(393.0, 0.5)])
C=(k*lHe/(d**2 + lHe**2)**(1/2))*10**6 #Comprimento de Onda (nm)
C

array([456.7911055168428+/-0.5582805508971024,
       479.2857666075383+/-0.578865242094198,
       501.49848242388987+/-0.5986319461210365,
       516.1463202267588+/-0.6113423514869543,
       580.4106946521044+/-0.6637563602651952,
       681.2041319642155+/-0.7333185164689523], dtype=object)

In [7]:
f=c/C*10**(-3)
f #Frequência

array([656.3009970625317+/-0.802117374373608,
       625.4983537733224+/-0.7554558912720729,
       597.7933503427862+/-0.7135778257279717,
       580.8284322714769+/-0.6879541821383638,
       516.5178049996034+/-0.590688595881581,
       440.0919547207744+/-0.4737604547629387], dtype=object)

In [8]:
E=h*f
E # Energia

array([4.351275610524584e-31+/-5.318038192097021e-34,
       4.147054085517127e-31+/-5.008672559133843e-34,
       3.963369912772672e-31+/-4.731020984576451e-34,
       3.8508925059598914e-31+/-4.561136227577352e-34,
       3.42451304714737e-31+/-3.9162653906948815e-34,
       2.917809659798734e-31+/-3.1410318150782836e-34], dtype=object)